#!/usr/bin/env python

from sys import argv, exit, stdout
from os import listdir, chdir, getcwd, makedirs
from os.path import isfile, join, exists
from re import sub
from numpy import array, mean, math, pi
from traceback import print_exc
from math import sqrt, log10

files_paths = []

def hermite_poly(deg, var):
	try:
		poly_val = 0.0

		if deg == 0:
			poly_val = 1.0
		elif deg == 1:
			poly_val = var
		else:
			poly_val = var*hermite_poly(deg - 1, var) - (deg - 1)*hermite_poly(deg - 2, var) 

		return poly_val
	except:
		print_exc(file = stdout)
		exit(0)

def nodes_weights(deg):
	nodes = []
	weights = []

	if deg == 1:
		nodes.append(0.0)
		weights.append(1.7725)
			
	elif deg == 1:
		nodes.append(-0.7071)
		nodes.append(0.7071)
		weights.append(0.8862)
		weights.append(0.8862)
		
	elif deg == 3:
		nodes.append(-1.2247)
		nodes.append(0.0000)
		nodes.append(1.2247)
		weights.append(0.2954)
		weights.append(1.1816)
		weights.append(0.2954)
		
	elif deg == 4:
		nodes.append(-1.6507)
		nodes.append(-0.5246)
		nodes.append(0.5246)
		nodes.append(1.6507)
		weights.append(0.0813)
		weights.append(0.8049)
		weights.append(0.8049)
		weights.append(0.0813)
		
	elif deg == 5:
		nodes.append(-2.0202)
		nodes.append(-0.9586)
		nodes.append(0.0)
		nodes.append(0.9586)
		nodes.append(2.0202)
		weights.append(0.0200)
		weights.append(0.3936)
		weights.append(0.9453)
		weights.append(0.3936)
		weights.append(0.0200)
		
	elif deg == 6:
		nodes.append(-2.3506)
		nodes.append(-1.3358)
		nodes.append(-0.4361)
		nodes.append(0.4361)
		nodes.append(1.3358)
		nodes.append(2.3506)
		weights.append(0.0045)
		weights.append(0.1571)
		weights.append(0.7246)
		weights.append(0.7246)
		weights.append(0.1571)
		weights.append(0.0045)
		
	elif deg == 7:
		nodes.append(-2.6520)
		nodes.append(-1.6736)
		nodes.append(-0.8163)
		nodes.append(0.0000)
		nodes.append(0.8163)
		nodes.append(1.6736)
		nodes.append(2.6520)
		weights.append(0.0010)
		weights.append(0.0545)
		weights.append(0.4256)
		weights.append(0.8103)
		weights.append(0.4256)
		weights.append(0.0545)
		weights.append(0.0010)
		
	elif deg == 8:
		nodes.append(-2.9306)
		nodes.append(-1.9817)
		nodes.append(-1.1572)
		nodes.append(-0.3812)
		nodes.append(0.3812)
		nodes.append(1.1572)
		nodes.append(1.9817)
		nodes.append(2.9306)
		weights.append(0.0002)
		weights.append(0.0171)
		weights.append(0.2078)
		weights.append(0.6611)
		weights.append(0.6611)
		weights.append(0.2078)
		weights.append(0.0171)
		weights.append(0.0002)
		
	elif deg == 9:
		nodes.append(-3.1910)
		nodes.append(-2.2666)
		nodes.append(-1.4686)
		nodes.append(-0.7236)
		nodes.append(0.0)
		nodes.append(0.7236)
		nodes.append(1.4686)
		nodes.append(2.2666)
		nodes.append(3.1910)
		weights.append(0.0000)
		weights.append(0.0049)
		weights.append(0.0885)
		weights.append(0.4327)
		weights.append(0.7202)
		weights.append(0.4327)
		weights.append(0.0885)
		weights.append(0.0049)
		weights.append(0.0000)
		
	elif deg == 10:
		nodes.append(-3.4362)
		nodes.append(-2.5327)
		nodes.append(-1.7567)
		nodes.append(-1.0366)
		nodes.append(-0.3429)
		nodes.append(0.3429)
		nodes.append(1.0366)
		nodes.append(1.7567)
		nodes.append(2.5327)
		nodes.append(3.4362)
		weights.append(0.0000)
		weights.append(0.0013)
		weights.append(0.0339)
		weights.append(0.2401)
		weights.append(0.6109)
		weights.append(0.6109)
		weights.append(0.2401)
		weights.append(0.0339)
		weights.append(0.0013)
		weights.append(0.0000)

	else:
		print "Please input a smaller quadrature degree!"
		exit(0)

	nodes = array(nodes)
	weights = array(weights)

	return nodes, weights

def nodes_weights_2D(no_of_simulations_1D):
	nodes_1D, weights_1D = nodes_weights(no_of_simulations_1D)
	weights_2D = []
	nodes_2D = [[0. for x in range(no_of_simulations_1D*no_of_simulations_1D)] for x in range(2)]

	for i in range(no_of_simulations_1D):
		for j in range(no_of_simulations_1D):
			weights_2D.append(weights_1D[i]*weights_1D[j])

	for i in range(no_of_simulations_1D):
		for j in range(no_of_simulations_1D):
			nodes_2D[0][i*no_of_simulations_1D + j] = nodes_1D[i]

	for i in range(no_of_simulations_1D):
		for j in range(no_of_simulations_1D):
			nodes_2D[1][i*no_of_simulations_1D + j] = nodes_1D[j]

	return nodes_2D, weights_2D

def mindex_dict():
	mindex = {0:(0, 0), 1:(1, 0), 2:(0, 1), 3:(2, 0), 4:(1, 1), 5:(0, 2), 6:(3, 0), 7:(2, 1), 8:(1, 2), 9:(0, 3), 10:(4, 0), 11:(3, 1), 12:(2, 2), 13:(1, 3), 14:(0, 4)}

	return mindex

def multi_hermite_poly(poly_index, deg, var1, var2):

	return hermite_poly(deg[0], sqrt(2.)*var1)*hermite_poly(deg[1], sqrt(2.)*var2)/(sqrt(norm_factor(deg[0]))*sqrt(norm_factor(deg[1])))
		
def norm_factor(deg):

	return math.factorial(deg)

def import_datafiles(no_of_simulations, base_path, files_type):
	files = []
	files_all = []
	files_no = []

	try:
		for i in range(no_of_simulations):
			files_path = base_path + str(i)
			files_paths.append(files_path)

			files = [ f for f in listdir(files_path) if f.startswith(files_type) ]
			files.sort()
			files_all.append(files_path)
			files_all.append(files)

		for _file in files:
			file_no = sub(files_type, '', _file)
			files_no.append(file_no)
			files_no.sort()
	except:
		print_exc(file = stdout)
		exit(0)

	return files_all, files_no

def get_same_files(no_of_simulations, all_files, files_type, files_no, dim):
	all_same_files = []

	try:
		if dim != 0:
			for i in range(dim):
				list_of_same_files = 'data_file_' + str(i)
				list_of_same_files = []

				for one_sim_files in all_files:

					for path in files_paths:
						if path == one_sim_files:
							name = one_sim_files

					for sim_files in one_sim_files:
						file_name = files_type + files_no[i]

						if sim_files == file_name:
							list_of_same_files.append(name)
							list_of_same_files.append(sim_files)

				all_same_files.append(list_of_same_files)
	except:
		print_exc(file = stdout)
		exit(0)

	return all_same_files

def get_coefficients(all_same_files, out_path, no_of_simulations, no_of_coefficients, mindex, out_file, line_veloc):
	no_of_simulations_1D = int(sqrt(no_of_simulations))
	nodes, weights = nodes_weights_2D(no_of_simulations_1D)

	try:
		for j in range(no_of_coefficients):
			out_path = out_path + str(j)
			
			if not exists(out_path):
				makedirs(out_path)

			for files in all_same_files:
				length = len(files)

				data_veloc = []
				coeff_veloc = []

				for i in range(length):
					if i%2 == 0:
						for path in files_paths:
							if files[i] == path:
								path_to_file = files[i]
					else:
						data = []

						chdir(path_to_file)
						files_header = []

						with open(files[i], 'r') as data_file:
							for line_no, line in enumerate(data_file):
								if line[1].isdigit() or line[2].isdigit():
									if line_no == line_veloc:
										data.append(line)
					
						data = [float(item) for item in data]
						
						data_file.close()

						back_path = ''	
						for i in range(len(path_to_file.split('/'))):
							back_path += '../'

						chdir(back_path)

						data_veloc.append(data)

				# after gathering data from all same files, perform numerical quadrature
				for num_sol_value in zip(*data_veloc):
					coeff = 0.

					for i in range(no_of_simulations):
						coeff += num_sol_value[i]*multi_hermite_poly(j, mindex[j], nodes[0][i], nodes[1][i])*weights[i]/pi

					coeff_veloc.append(coeff)

				chdir(out_path)

				with open(out_file, 'a') as veloc_file:
					for item in coeff_veloc:
						veloc_file.write(str(item) + '\n')
				
				veloc_file.close()

				back_path = ''	
				for i in range(len(out_path.split('/'))):
					back_path += '../'
					
				chdir(back_path)

			if j == 0:
				out_path = out_path[:-1]
			else:
				out_path = out_path[:-(int(log10(j))+1)]

	except:
		print_exc(file = stdout)
		exit(0)

if __name__=="__main__":

	if len(argv) != 7:
		print "Error in " + argv[0] + "!"
		print "Usage: " + argv[0] + " data_path out_path out_file no_of_simulations no_of_coefficients line_veloc"
		exit(0)

	path =  argv[1]
	out_path = argv[2]
	out_file = argv[3]
	no_of_simulations = int(argv[4])
	no_of_coefficients = int(argv[5])
	line_veloc = int(argv[6])

	files_type = 'Flap.ensi.VELOC'

	all_filess, files_no = import_datafiles(no_of_simulations, path, files_type)
	dim = len(files_no)

	mindex =  mindex_dict() 

	all_same_files =  get_same_files(no_of_simulations, all_filess, files_type, files_no, dim)	
	get_coefficients(all_same_files, out_path, no_of_simulations, no_of_coefficients, mindex, out_file, line_veloc)