#!/usr/bin/env python

# script used for getting the quantities of interest (qoi) out of the collective 
# datafile and plot them; for the current setting, the qoi are the displacement
# on the x axis and force 0 and force 1

from os import rename, remove
from sys import argv, exit, stdout
from traceback import print_exc
from matplotlib.pyplot import *
from pylab import plot, show
import numpy as np
from scipy import stats
from statsmodels.api import qqplot, nonparametric
from pylab import plot, show

def parse_sc_file(datafile, no_of_coeff):
	mean_disp_x_all = []
	var_disp_x_all = []
	mean_f0_all = []
	var_f0_all = []
	mean_f1_all = []
	var_f1_all = []

	displacement_x = []
	forces0 = []
	forces1 = []

	timestep_disp_x = []
	timestep_forces0 = []
	timestep_forces1 = []

	m_disp_x = 0.
	var_disp_x = 0.
	m_f0_x = 0.
	var_f0_x = 0.
	m_f1_x = 0.
	var_f1_x = 0.

	try:
		with open(datafile, 'r') as input_file:
			for line in input_file:

					line_tokens = line.split()

					displacement_x.append(line_tokens[0])
					forces0.append(line_tokens[1])
					forces1.append(line_tokens[2])

			displacement_x = np.array(displacement_x)
			displacement_x = displacement_x.astype(np.float)
			forces0 = np.array(forces0)
			forces0 = forces0.astype(np.float)
			forces1 = np.array(forces1)
			forces1 = forces1.astype(np.float)

			no_of_timesteps = len(displacement_x)/no_of_coeff

			for i in range(no_of_timesteps):
				for j in range(no_of_coeff):

					timestep_disp_x.append(displacement_x[i*no_of_coeff + j])
					timestep_forces0.append(forces0[i*no_of_coeff + j])
					timestep_forces1.append(forces1[i*no_of_coeff + j])

				timestep_disp_x = np.array(timestep_disp_x)
				timestep_disp_x = timestep_disp_x.astype(np.float)
				timestep_forces0 = np.array(timestep_forces0)
				timestep_forces0 = timestep_forces0.astype(np.float)
				timestep_forces1 = np.array(timestep_forces1)
				timestep_forces1 = timestep_forces1.astype(np.float)

				m_disp_x = timestep_disp_x[0]
				var_disp_x = np.sum(coeff**2 for coeff in timestep_disp_x) - m_disp_x**2
				m_f0 = timestep_forces0[0]
				var_f0 = np.sum(coeff**2 for coeff in timestep_forces0) - m_f0**2
				m_f1 = timestep_forces1[0]
				var_f1 = np.sum(coeff**2 for coeff in timestep_forces1) - m_f1**2

				mean_disp_x_all.append(m_disp_x)
				var_disp_x_all.append(var_disp_x)
				mean_f0_all.append(m_f0)
				var_f0_all.append(var_f0)
				mean_f1_all.append(m_f1)
				var_f1_all.append(var_f1)

				timestep_disp_x = []
				timestep_forces0 = []
				timestep_forces1 = []

		input_file.close()
		
	except IOError:
		print_exc(file = stdout)
		exit(0)

	return mean_disp_x_all, var_disp_x_all, mean_f0_all, var_f0_all, mean_f1_all, var_f1_all

def H_test(par1, par2, par3):

	est_pdf = nonparametric.KDEUnivariate(par2)
	est_pdf.fit(kernel="gau")

	# plot(est_pdf.support, est_pdf.density)
	# show()

	F1, p1 = stats.f_oneway(par1, par3)
	F2, p2 = stats.f_oneway(par2, par3)

	print 'p(par1, par3) = '
	print p1

	print 'p(par2, par3) = '
	print p2
	
if __name__ == "__main__":

	if len(argv) != 7:
		print "Error in " + argv[0] + "!"
		print "Usage: " + argv[0] + " datafile_x no_of_coeff_x, x = 1..." + str(3)
		exit(0)

	datafile1 = argv[1]
	datafile2 = argv[3]
	datafile3 = argv[5]

	no_of_coeff_1 = int(argv[2])
	no_of_coeff_2 = int(argv[4])
	no_of_coeff_3 = int(argv[6])

	mean_disp_x_all_1, var_disp_x_all_1, mean_f0_all_1, var_f0_all_1, mean_f1_all_1, var_f1_all_1 = parse_sc_file(datafile1, no_of_coeff_1)
	mean_disp_x_all_2, var_disp_x_all_2, mean_f0_all_2, var_f0_all_2, mean_f1_all_2, var_f1_all_2 = parse_sc_file(datafile2, no_of_coeff_2)
	mean_disp_x_all_3, var_disp_x_all_3, mean_f0_all_3, var_f0_all_3, mean_f1_all_3, var_f1_all_3 = parse_sc_file(datafile3, no_of_coeff_3)

	print 'comparing disp x mean'
	H_test(mean_disp_x_all_1, mean_disp_x_all_2, mean_disp_x_all_3)
	print 'comparing disp x var'
	H_test(var_disp_x_all_1, var_disp_x_all_2, var_disp_x_all_3)

	# H_test(mean_f0_all_1, mean_f0_all_2, mean_f0_all_3)
	# H_test(var_f0_all_1, var_f0_all_2, var_f0_all_3)

	# H_test(mean_f1_all_1, mean_f1_all_2, mean_f1_all_3)
	# H_test(var_f1_all_1, var_f1_all_2, var_f1_all_3)