#!/usr/bin/env python

# script used for inserting new numerical values for the physical parameters 
# from the fluid and structure problems; 
# e.g. density and viscosity for the fluid problem and density for the structure problem
# new values given in the command line

from os import rename, remove
from sys import argv, exit, stdout
from traceback import print_exc

newline = '\n'
space = ' '

# append data
def gather_data(simulation_no):

	try:
		with open(datafile, 'r') as input_file:
			with open(datafile_output, 'w') as output_file:
				line = "DATA FROM SIMULATION " + str(simulation_no) + newline
				output_file.write(line)

				lines = input_file.readlines()

				for line in lines:
					tokens = line.split()
					if len(tokens) !=0 :
						output_file.write(tokens[3] + space + tokens[7] + space + tokens[8] + newline)

		input_file.close()
		output_file.close()

	except IOError:
		print_exc(file = stdout)
		exit(0)

if __name__ == "__main__":

	# take command line arguments; variable names show which parameters are to be modified

	if len(argv) != 4:
		print "Error in " + argv[0] + "!"
		print "Usage: " + argv[0] + " datafile datafile_output simulation_no"
		exit(0)

	datafile = argv[1]
	datafile_output = argv[2]
	simulation_no = argv[3]

	gather_data(simulation_no)