#!/bin/bash

if [ $# -eq 1 ]; 
then
	if [ -d "../../simulation_$1/" ]; 
	then 
		rm -r ../../simulation_$1
	fi

	if [ -d "../../simulation_$1/nastin_$1" ]; 
	then
		rm -r ../../simulation_$1/nastin_$1
	fi

	mkdir ../../simulation_$1/

	mkdir ../../simulation_$1/nastin_$1
	cp -r ../../nastin/* ../../simulation_$1/nastin_$1
	cp ../../precice-config.xml ../../simulation_$1/

	if [ -d "../../simulation_$1/solidz_$1" ]; 
	then
		rm -r ../../simulation_$1/solidz_$1
	fi
	
	mkdir ../../simulation_$1/solidz_$1
	cp -r ../../solidz/* ../../simulation_$1/solidz_$1
	cp ../../precice-config.xml ../../simulation_$1/
else
	echo "Error when using $0!"
	echo "Correct usage: $0 point"
fi