#!/usr/bin/perl

use autodie;
use strict;
use warnings qw(all);

if ($#ARGV != 1 ) 
{
	print "Error!\nUsage: ./insert_params_nastin_1d FILE_NAME new_visosity\n";
	exit;
}

my $file = $ARGV[0];
my $viscosity = $ARGV[1];

my $viscosity_line = 13;

@ARGV = ($file);
$^I = "";

while (<>)
{
    if ($. == $viscosity_line) 
    {
        my $line = "\t VISCOSITY= $viscosity\n";
        print $line;
    }
    else
    {
    	print;
    }
}
