#!/usr/bin/env python

# script used for getting the quantities of interest (qoi) out of the collective 
# datafile and plot them; for the current setting, the qoi are the displacement
# on the x axis and force 0 and force 1

from os import rename, remove
from sys import argv, exit, stdout
from traceback import print_exc
import matplotlib.pyplot as plt
import numpy as np

newline = str('\n')

# get qoi
def gather_qoi():

	displacement_x = []
	forces0 = []
	forces1 = []

	m_disp_x = 0.
	var_disp_x = 0.
	m_f0_x = 0.
	var_f0_x = 0.
	m_f1_x = 0.
	var_f1_x = 0.

	try:
		with open(datafile, 'r') as input_file:
			with open(statistics, 'w') as output_file:

				for line in input_file:

						line_tokens = line.split()

						displacement_x.append(line_tokens[0])
						forces0.append(line_tokens[1])
						forces1.append(line_tokens[2])

				displacement_x = np.array(displacement_x)
				displacement_x = displacement_x.astype(np.float)
				forces0 = np.array(forces0)
				forces0 = forces0.astype(np.float)
				forces1 = np.array(forces1)
				forces1 = forces1.astype(np.float)

				m_disp_x = displacement_x[0]
				var_disp_x = np.sum(coeff**2 for coeff in displacement_x) - m_disp_x**2
				m_f0 = forces0[0]
				var_f0 = np.sum(coeff**2 for coeff in forces0) - m_f0**2
				m_f1 = forces1[0]
				var_f1 = np.sum(coeff**2 for coeff in forces1) - m_f1**2

				stat = "The mean of the displacement on the x axis is: " + str(m_disp_x) + newline
				output_file.write(stat)
				stat = "The variance of the displacement on the x axis is: " + str(var_disp_x) + newline
				output_file.write(stat)
				output_file.write(newline)
				
				stat = "The mean of force 0 is:" + str(m_f0) + newline
				output_file.write(stat)
				stat = "The variance of force 0 is: " + str(var_f0) + newline
				output_file.write(stat)
				output_file.write(newline)

				stat = "The mean of forces 1 is: " + str(m_f1) + newline
				output_file.write(stat)
				stat = "The variance of force 1 is: " + str(var_f1) + newline
				output_file.write(stat)
				output_file.write(newline)

		input_file.close()
		output_file.close()

		plt.close('all')

		f, axarr = plt.subplots(3)

		axarr[0].plot(displacement_x, 'r--')
		axarr[0].set_title('Displacement on the x axis')
		axarr[1].plot(forces0, 'g--')
		axarr[1].set_title('Force 0')
		axarr[2].plot(forces1, 'b--')
		axarr[2].set_title('Force 1')

		plt.grid(True)

		plt.show()

		f.savefig("../tools/postprocessing/results/scsim.png")
				
	except IOError:
		print_exc(file = stdout)
		exit(0)

if __name__ == "__main__":

	if len(argv) != 3:
		print "Error in processing_stat!"
		print "Usage: " + argv[0] + " datafile statistics_file"
		exit(0)

	datafile = argv[1]
	statistics = argv[2]

	gather_qoi()

